### ISSUE TITLE
Errors encountered when using Dragonfly #2 (Abortive)

### ISSUE THREAD

**Issue by alelasantillan** [dragonfly/dragonfly#34]
This is the second type of error abortive I found (AssertionError):

/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_ataa/lib/python3.7/site-packages/dragonfly/gp/gp_core.py:184: RuntimeWarning: invalid value encountered in sqrt
  uncert = np.sqrt(np.diag(post_covar))
Traceback (most recent call last):
  File "in_code_demo_alela2.py", line 36, in <module>
    main()
  File "in_code_demo_alela2.py", line 31, in main
    opt_val, opt_pt, _ = minimise_function(my_func_to_minimize, config.domain, max_capital, config=config) #alela
  File "/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_ataa/lib/python3.7/site-packages/dragonfly/apis/opt.py", line 215, in minimise_function
    max_val, opt_pt, history = maximise_function(func_to_max, *args, **kwargs)
  File "/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_ataa/lib/python3.7/site-packages/dragonfly/apis/opt.py", line 178, in maximise_function
    max_capital, is_mf=False, options=options, reporter=reporter)
  File "/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_ataa/lib/python3.7/site-packages/dragonfly/opt/gp_bandit.py", line 1000, in gpb_from_func_caller
    return optimiser.optimise(max_capital)
  File "/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_ataa/lib/python3.7/site-packages/dragonfly/opt/blackbox_optimiser.py", line 189, in optimise
    return self.run_experiments(max_capital)
  File "/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_ataa/lib/python3.7/site-packages/dragonfly/exd/exd_core.py", line 536, in run_experiments
    self._asynchronous_run_experiment_routine()
  File "/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_ataa/lib/python3.7/site-packages/dragonfly/exd/exd_core.py", line 494, in _asynchronous_run_experiment_routine
    self._dispatch_single_experiment_to_worker_manager(qinfo)
  File "/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_ataa/lib/python3.7/site-packages/dragonfly/exd/exd_core.py", line 404, in _dispatch_single_experiment_to_worker_manager
    self.worker_manager.dispatch_single_experiment(self.experiment_caller, qinfo)
  File "/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_ataa/lib/python3.7/site-packages/dragonfly/exd/worker_manager.py", line 189, in dispatch_single_experiment
    qinfo = self._dispatch_experiment(func_caller, qinfo, worker_id, **kwargs)
  File "/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_ataa/lib/python3.7/site-packages/dragonfly/exd/worker_manager.py", line 173, in _dispatch_experiment
    qinfo = func_caller.eval_from_qinfo(qinfo, **kwargs)
  File "/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_ataa/lib/python3.7/site-packages/dragonfly/exd/experiment_caller.py", line 221, in eval_from_qinfo
    _, qinfo = self.eval_single(qinfo.point, qinfo, *args, **kwargs)
  File "/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_ataa/lib/python3.7/site-packages/dragonfly/exd/experiment_caller.py", line 166, in eval_single
    true_val = self._get_true_val_from_experiment_at_point(point)
  File "/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_ataa/lib/python3.7/site-packages/dragonfly/exd/experiment_caller.py", line 146, in _get_true_val_from_experiment_at_point
    assert self.domain.is_a_member(point)
AssertionError

**Comment by alelasantillan** [comment]
See this issue: https://github.com/dragonfly/dragonfly/issues/33#
