### ISSUE TITLE
Error encountered while using Dragonfly #5 (Abortive)

### ISSUE THREAD

**Issue by alelasantillan** [dragonfly/dragonfly#37]
See this issue: https://github.com/dragonfly/dragonfly/issues/33#

Another error that aborts execution:

Traceback (most recent call last):
  File "in_code_demo_alela2.py", line 37, in <module>
    main()
  File "in_code_demo_alela2.py", line 32, in main
    opt_val, opt_pt, _ = minimise_function(my_func_to_minimize, config.domain, max_capital, config=config) #alela
  File "/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_ataa/lib/python3.7/site-packages/dragonfly/apis/opt.py", line 215, in minimise_function
    max_val, opt_pt, history = maximise_function(func_to_max, *args, **kwargs)
  File "/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_ataa/lib/python3.7/site-packages/dragonfly/apis/opt.py", line 178, in maximise_function
    max_capital, is_mf=False, options=options, reporter=reporter)
  File "/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_ataa/lib/python3.7/site-packages/dragonfly/opt/gp_bandit.py", line 1000, in gpb_from_func_caller
    return optimiser.optimise(max_capital)
  File "/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_ataa/lib/python3.7/site-packages/dragonfly/opt/blackbox_optimiser.py", line 189, in optimise
    return self.run_experiments(max_capital)
  File "/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_ataa/lib/python3.7/site-packages/dragonfly/exd/exd_core.py", line 536, in run_experiments
    self._asynchronous_run_experiment_routine()
  File "/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_ataa/lib/python3.7/site-packages/dragonfly/exd/exd_core.py", line 491, in _asynchronous_run_experiment_routine
    qinfo = self._determine_next_query()
  File "/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_ataa/lib/python3.7/site-packages/dragonfly/opt/gp_bandit.py", line 495, in _determine_next_query
    next_eval_point = select_pt_func(self.gp, anc_data)
  File "/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_ataa/lib/python3.7/site-packages/dragonfly/opt/gpb_acquisitions.py", line 294, in asy_ttei
    return _ttei(gp_eval, anc_data, ei_argmax)
  File "/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_ataa/lib/python3.7/site-packages/dragonfly/opt/gpb_acquisitions.py", line 271, in _ttei
    ref_mean, ref_std = gp_eval([ref_point])
  File "/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_ataa/lib/python3.7/site-packages/dragonfly/opt/gpb_acquisitions.py", line 55, in <lambda>
    return lambda x: _gp.eval(x, uncert_form=_uncert_form)
  File "/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_ataa/lib/python3.7/site-packages/dragonfly/gp/gp_core.py", line 170, in eval
    K_tetr = self.kernel(X_test, self.X)
  File "/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_ataa/lib/python3.7/site-packages/dragonfly/gp/kernel.py", line 74, in __call__
    return self.evaluate(X1, X2)
  File "/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_ataa/lib/python3.7/site-packages/dragonfly/gp/kernel.py", line 83, in evaluate
    return self._child_evaluate(X1, X2)
  File "/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_ataa/lib/python3.7/site-packages/dragonfly/gp/kernel.py", line 530, in _child_evaluate
    curr_X1 = get_idxs_from_list_of_lists(X1, idx)
  File "/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_ataa/lib/python3.7/site-packages/dragonfly/utils/general_utils.py", line 45, in get_idxs_from_list_of_lists
    return [elem[idx] for elem in list_of_lists]
  File "/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_ataa/lib/python3.7/site-packages/dragonfly/utils/general_utils.py", line 45, in <listcomp>
    return [elem[idx] for elem in list_of_lists]
TypeError: 'NoneType' object is not subscriptable

**Comment by alelasantillan** [comment]
See this issue: https://github.com/dragonfly/dragonfly/issues/33#
