### ISSUE TITLE
What is the version of tensorflow is used in neural architecture search?

### ISSUE THREAD

**Issue by auroua** [dragonfly/dragonfly#61]
What is the version of tensorflow is used in neural architecture search? 
I'm using tensorflow 1.14.0 and running code `demo_nas.py` encountered the following error:

```
  File "/home/albert_wei/WorkSpaces_2020/dragonfly-master/dragonfly/exd/exd_core.py", line 707, in run_experiments
    self.run_experiment_initialise()
  File "/home/albert_wei/WorkSpaces_2020/dragonfly-master/dragonfly/exd/exd_core.py", line 466, in run_experiment_initialise
    self.perform_initial_queries()
  File "/home/albert_wei/WorkSpaces_2020/dragonfly-master/dragonfly/exd/exd_core.py", line 350, in perform_initial_queries
    self._wait_for_a_free_worker()
  File "/home/albert_wei/WorkSpaces_2020/dragonfly-master/dragonfly/exd/exd_core.py", line 497, in _wait_for_a_free_worker
    self.worker_manager.get_poll_time_real())
  File "/home/albert_wei/WorkSpaces_2020/dragonfly-master/dragonfly/exd/exd_core.py", line 487, in _wait_till_free
    self._update_history(qinfo)
  File "/home/albert_wei/WorkSpaces_2020/dragonfly-master/dragonfly/exd/exd_core.py", line 229, in _update_history
    self._exd_child_update_history(qinfo)
  File "/home/albert_wei/WorkSpaces_2020/dragonfly-master/dragonfly/opt/blackbox_optimiser.py", line 95, in _exd_child_update_history
    self._update_opt_point_and_val(qinfo, query_is_at_fidel_to_opt)
  File "/home/albert_wei/WorkSpaces_2020/dragonfly-master/dragonfly/opt/blackbox_optimiser.py", line 118, in _update_opt_point_and_val
    if qinfo.val > self.curr_opt_val:
TypeError: '>' not supported between instances of 'str' and 'float'
```
How to fix this error? Thanks.

**Comment by auroua** [comment]
I found the following output in `log.txt`.
```
Optimisation with mfbo-boca(ei-ucb-ttei) using capital 28800.0 (realtime)
 -- Failed on try 1 with gpu 0: viewkeys not found.
 -- Failed on try 2 with gpu 0: viewkeys not found.
 -- Failed on try 3 with gpu 0: viewkeys not found.
Exception when evaluating [40] at fidel [<dragonfly.nn.neural_network.ConvNeuralNetwork object at 0x7fbaae1a5c50>, -4.329887871112025]: local variable 'vali_error' referenced before assignment.
```
I use a computer with one gpu and works fine.

**Comment by auroua** [comment]
I also tested the code in repository `nasbot`, and the code seems can not run on gpu. I have set the gpu id correctly.

**Comment by auroua** [comment]
The code in `nasbot` report the following errors:
```
********* Failed on try 2 with gpu 0.
Traceback (most recent call last):
  File "/home/albert_wei/WorkSpaces_2020/nasbot/demos/cnn_function_caller.py", line 51, in _eval_validation_score
    qinfo.worker_id, self.train_params.tf_params, self.tmp_dir)
  File "/home/albert_wei/WorkSpaces_2020/nasbot/cg/cifar/run_tensorflow_cifar.py", line 74, in compute_validation_error
    model.train(train_input_fn,steps=params['trainNumStepsPerLoop'])
  File "/home/albert_wei/Softwares/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 367, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/albert_wei/Softwares/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1158, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/albert_wei/Softwares/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1192, in _train_model_default
    saving_listeners)
  File "/home/albert_wei/Softwares/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1484, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/home/albert_wei/Softwares/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 754, in run
    run_metadata=run_metadata)
  File "/home/albert_wei/Softwares/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1252, in run
    run_metadata=run_metadata)
  File "/home/albert_wei/Softwares/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1353, in run
    raise six.reraise(*original_exc_info)
  File "/home/albert_wei/Softwares/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1338, in run
    return self._sess.run(*args, **kwargs)
  File "/home/albert_wei/Softwares/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1411, in run
    run_metadata=run_metadata)
  File "/home/albert_wei/Softwares/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1169, in run
    return self._sess.run(*args, **kwargs)
  File "/home/albert_wei/Softwares/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/albert_wei/Softwares/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/albert_wei/Softwares/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/albert_wei/Softwares/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
InvalidArgumentError: Default MaxPoolingOp only supports NHWC on device type CPU
	 [[node cnn/device_0/max_pool/max_pooling2d/MaxPool (defined at /WorkSpaces_2020/nasbot/cg/cifar/cifar10_model_base.py:161) ]]
```
How to fix this error?
Thanks.

**Comment by kirthevasank** [comment]
The dragonfly NAS examples run with tensorflow 1.5. See the readme here: https://github.com/dragonfly/dragonfly/tree/master/examples/nas

**Comment by auroua** [comment]
Thanks?
What about `nasbot`?

**Comment by auroua** [comment]
The `dok_matrix` in `python3.6` does not contain `viewkeys`
How to fix the `viewkeys` error?
```
In [2]: a = dok_matrix((5, 5))                                                  

In [3]: a.viewkeys()                                                            
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-0de521f17006> in <module>
----> 1 a.viewkeys()

~/Softwares/anaconda3/envs/py36/lib/python3.6/site-packages/scipy/sparse/base.py in __getattr__(self, attr)
    689             return self.getnnz()
    690         else:
--> 691             raise AttributeError(attr + " not found")
    692 
    693     def transpose(self, axes=None, copy=False):

AttributeError: viewkeys not found

```
