### ISSUE TITLE
Installation Problems on ARM64

### ISSUE THREAD

**Issue by EliaSavino** [dragonfly/dragonfly#98]
Hello!

I am reaching out for assistance with an issue I'm encountering while trying to install a package within a virtual environment using Python 3.11.3. I have followed all the installation instructions available in the documentation on Read the Docs and GitHub. Additionally, I have ensured that numpy is installed within the virtual environment.

However, I am running into the following error when attempting the installation:

```
Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "/Path/to/env/environment/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Path/to/env/environment/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Path/to/env/environment/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/w1/sr8kym7n5lq78dc9m2pkk65w0000gn/T/pip-build-env-0aieq2x6/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/w1/sr8kym7n5lq78dc9m2pkk65w0000gn/T/pip-build-env-0aieq2x6/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/w1/sr8kym7n5lq78dc9m2pkk65w0000gn/T/pip-build-env-0aieq2x6/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/w1/sr8kym7n5lq78dc9m2pkk65w0000gn/T/pip-build-env-0aieq2x6/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 6, in <module>
      ModuleNotFoundError: No module named 'numpy'
      [end of output]

```

Here are the installation methods I tried, they all result in the same error:
```
1) pip install dragonfly-opt
2) pip install drangonfly-opt -v
3) pip install git+https://github.com/dragonfly/dragonfly.git 
```

I would greatly appreciate any guidance or insights on how to resolve this issue.

Thank you for your time and assistance.

Best regards,

Elia

P.S. The installation attempt is done on a MacOS Ventura M2-pro chip (not sure if it matters, but good to know)

**Comment by EliaSavino** [comment]
Fixed, Thanks
